[package]
name = "seal-story-painter-backend"
version = "0.1.0"
authors = ["JustAnotherID <just-another-id@outlook.com>"]
edition = "2021"

[workspace]
members = [
    ".", "entity",
    "entity",
    "migration"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }

anyhow = "^1.0.89"
axum = { version = "^0.7.7", features = ["http2", "multipart"] }
base64 = "^0.22.1"
clap = { version = "^4.5.19", features = ["derive"] }
console = { version = "^0.15.8", features = ["windows-console-colors"] }
dialoguer = "^0.11.0"
flate2 = { version = "1.0.34" }
log = { version = "^0.4.22", features = ["serde"] }
nid = { version = "^3.0.0", features = ["serde"] }
sea-orm = { version = "^1.0.1", features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-postgres",
    "sqlx-sqlite",
    "with-json",
    "with-time",
] }
serde = { version = "^1.0.210", features = ["derive"] }
serde_json = { version = "^1.0.128", features = ["raw_value"] }
time = { version = "^0.3.36", features = ["serde-human-readable"] }
toml = "^0.8.19"
tokio = { version = "^1.40.0", features = ["full"] }
tower = "^0.5.1"
tower-http = { version = "^0.6.1", features = ["cors", "trace"] }
tracing = "^0.1.40"
tracing-subscriber = { version = "^0.3.18", features = ["env-filter", "local-time"] }

[dev-dependencies]
http-body-util = "^0.1.2"
