//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extension_tag_relation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub extension_id: i32,
    pub tag_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::extension::Entity",
        from = "Column::ExtensionId",
        to = "super::extension::Column::Id"
    )]
    Extension,

    #[sea_orm(
        belongs_to = "super::extension_tag::Entity",
        from = "Column::TagId",
        to = "super::extension_tag::Column::Id"
    )]
    ExtensionTag,
}

impl ActiveModelBehavior for ActiveModel {}
