//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "extension")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub outer_id: String,
    pub namespace: String,
    pub key: String,
    pub version: String,
    pub r#type: String,
    pub ext: String,
    pub name: String,
    pub authors: Json,
    #[sea_orm(column_type = "Text")]
    pub desc: String,
    pub license: String,
    pub release_time: i64,
    pub update_time: i64,
    pub download_num: i64,
    pub tags: Option<Json>,
    pub extra: Option<Json>,
    pub home_page: Option<String>,
    pub seal_version: Option<String>,
    pub dependencies: Option<Json>,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: Option<TimeDateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::extension_tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::extension_tag_relation::Relation::ExtensionTag.def()
    }

    fn via() -> Option<RelationDef> {
        Some(
            super::extension_tag_relation::Relation::Extension
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
