//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod dice_endpoint;
pub mod dice_info;
pub mod extension;
pub mod extension_tag;
pub mod extension_tag_relation;
pub mod file_info;
