//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::extension::Entity as Extension;
pub use super::extension_tag::Entity as ExtensionTag;
pub use super::extension_tag_relation::Entity as ExtensionTagRelation;
pub use super::file_info::Entity as FileInfo;
