//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::{
    dice_endpoint::Entity as DiceEndpoint, dice_info::Entity as DiceInfo,
    extension::Entity as Extension, extension_tag::Entity as ExtensionTag,
    extension_tag_relation::Entity as ExtensionTagRelation, file_info::Entity as FileInfo,
};
